### ISSUE TITLE
Create build for Linux Bash shell on Windows 10

### ISSUE THREAD

**Issue by noaaroland** [conda-forge/pyferret-feedstock#12]
PyFerret will install and run under the new Linux Bash shell on Windows 10 (Anniversary Edition).

Anaconda will install and run as well.

I would like to see the conda install for pyferret also work in the environment. Currently attempting to build the recipe as it is on this repository results in an dependency error for netcdf-fortran.

rhs@ZT:~/anaconda2$ conda build pyferret
Removing old build environment
BUILD START: pyferret-7.0.0-py27_4
    (actual version deferred until further download or env creation)
WARNING:/home/rhs/anaconda2/lib/python2.7/site-packages/conda_build/build.pyc:Your recipe depends on {} at build time (for templates), but you have not listed it as a build dependency.  Doing so for this build.
Error: Package missing in current linux-64 channels:
- netcdf-fortran 4.4.*
  rhs@ZT:

**Comment by ocefpaf** [comment]
> PyFerret will install and run under the new Linux Bash shell on Windows 10 (Anniversary Edition).

Those are good news. I haven't test that yet.

> I would like to see the conda install for pyferret also work in the environment.

Not sure what you mean by "the environment" there. But to build the recipe you need to make sure you are the `conda-forge` channel in your `.condarc` to get all the dependencies.

**Comment by noaaroland** [comment]
By "the environment", I mean this: https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/#4lgoFEGCYsucTdfK.97

I'm new to all this so you'll have to spell it all out for me. I don't find a .condarc file in my anaconda2 or home directory here.

Where should I look? Do I need to create one? How does one set the channel?

**Comment by ocefpaf** [comment]
Conda has the notion of `environments` for installing a different set of packages with a specific context. That is why I was confused.

> I don't find a .condarc file in my anaconda2 or home directory here.

It should be in your home. Not sure where that is on Windows bash. You can try:

``` shell
conda info
```

and look for something like

``` shell
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
```

If you cannot find the channel URLs for `conda-forge` you can try adding them with:

``` shell
conda config --add channels conda-forge --force
```

> Where should I look? Do I need to create one? How does one set the channel?

You will find the answer for many of those questions  in conda's docs.

http://conda.pydata.org/docs/intro.html

**Comment by noaaroland** [comment]
Hang on now...

I can try these things, but I'm not sure it's time to close this as yet.

**Comment by noaaroland** [comment]
It did work.

It's not clear to how to set up the Ferret environment in the Anaconda context, but the install worked after applying the directions in the [README ](https://github.com/conda-forge/pyferret-feedstock#installing-pyferret) (and detailed above). :-)

**Comment by ocefpaf** [comment]
> I can try these things, but I'm not sure it's time to close this as yet.

I closed because this is beyond the scope of the `feedstock`. But we can keep discussing here.

> It did work.

:tada: 

> It's not clear to how to set up the Ferret environment in the Anaconda context.

If you use conda environments everything should be set automatically for you. Try:

``` shell
conda create -n FERRET -c conda-forge pyferret --yes
source activate FERRET
echo $FER_DATA
```

You should see that `FER_DATA`, and all the other env vars expected, are (hopefuly) properly set for you. You should be able to just call `pyferret` and start using it.

PS: The `-n FERRET` is the name of the environment and `source activate FERRET` gets you inside that environment. To exit it you need type `source deactivate`.

**Comment by noaaroland** [comment]
Very nice.

This command: conda create -n FERRET -c conda-forge pyferret --yes
Downloads and installs the whole thing again, but once I made the data available where the environment said it should be located: anaconda2/envs/FERRET/share/fer_dsets/data I was able to open and plot COADS.

Sweet.

I think the bit about setting up the conda environment for FERRET should be on the home page along with the info about how to set up the channel and install.

**Comment by ocefpaf** [comment]
> Downloads and installs the whole thing again

Not really. It probably used the cached sources from your last install.

> I think the bit about setting up the conda environment for FERRET should be on the home page along with the info about how to set up the channel and install.

If you mean the `pyferret` page we can ping @karlmsmith for that. But if you mean the feedstock README (this reposiotry front page) we cannot do that because that README is auto-generated and has a fix format to match the other feedstocks.

**Comment by noaaroland** [comment]
Ok, maybe not download, but it sure looked like it did all the same actions of getting and unpacking the packages to set u the environment.

I was thinking of the feedstock page, but I see that it's not how it's done.

When we get ready to officially announce PyFerret via Anaconda we can put up the details for running it in that environment on the PyFerret page.

**Comment by ocefpaf** [comment]
> I was thinking of the feedstock page, but I see that it's not how it's done.

We have plans to allow custom text in the README but we haven't implemented that yet.

> When we get ready to officially announce PyFerret via Anaconda we can put up the details for running it in that environment on the PyFerret page.

:+1:

Thanks for testing that on Windows. I am glad it worked.

**Comment by eugeneburger** [comment]
@noaaroland and @ocefpaf  - this is great. Thank you both for making this happen.

@ocefpaf , a heads-up that @noaaroland is part of our Seattle group that includes @karlmsmith and me.

**Comment by ocefpaf** [comment]
> @ocefpaf , a heads-up that @noaaroland is part of our Seattle group that includes @karlmsmith and me.

Good to know. (And I asked him to get touch with you about the page :flushed:)

PS: I am really impressed with Windows 10 bash. I am actually testing that locally now. A game changer for Windows users.

**Comment by noaaroland** [comment]
Yeah, "game changer" is exactly how I described it. It's enough to make me seriously consider Windows again as a development environment.

**Comment by ocefpaf** [comment]
@noaaroland it will take a while until we can add extra information on the README regarding specific installation of each package. But we can open a new issue with some instructions and point people to that. Would that help you?
