### ISSUE TITLE
User with conda installation on RHEL5 hitting readline issue

### ISSUE THREAD

**Issue by karlmsmith** [conda-forge/pyferret-feedstock#16]
One of our users, Al, tried installing pyferret using

```
conda create -n PYFERRET -c conda-forge pyferret --yes
```

on his existing conda installation on an RHEL5 system.  (Hoping this is a way to use the latest PyFerret on his old system.)  When he runs, readline complains about the missing symbol PC.  

```
# To activate this environment, use:
# $ source activate PYFERRET
#
# To deactivate this environment, use:
# $ source deactivate
#
[hermannA@afsc-s45 ~]$ source activate PYFERRET
discarding /home/hermannA/anaconda2/bin from PATH
prepending /home/hermannA/anaconda2/envs/PYFERRET/bin to PATH
(PYFERRET)[hermannA@afsc-s45 ~]$ pyferret
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hermannA/anaconda2/envs/PYFERRET/lib/python2.7/site-packages/pyferret/__init__.py", line 40, in <module>
    import readline
ImportError: /home/hermannA/anaconda2/envs/PYFERRET/lib/python2.7/lib-dynload/../../libreadline.so.6: undefined symbol: PC
```

This sounds like the issue mentioned in 
[https://github.com/ContinuumIO/anaconda-issues/issues/152](https://github.com/ContinuumIO/anaconda-issues/issues/152)

The solution they mention is to link in the ncurses library when building.  FYI - because some of the comments mention the libtinfo.so library - RHEL (and Fedora, I assume) readline has this (weird) libtinfo.so requirement.  But their libncurses.so also requires that library.  Not that it matters if we are building our own readline and ncurses.

**Comment by ocefpaf** [comment]
@karlmsmith `conda-forge` uses a docker image with `CentOS 6` so I believe that is only the first of many  breakages expected when using packages on `RHEL5`. Sure if `conda-forge` can guarantee compatibility in that case.

**Comment by karlmsmith** [comment]
I was guessing there would be problems and figured this was a long shot.

**Comment by ocefpaf** [comment]
> I was guessing there would be problems and figured this was a long shot.

We discussed the possibility of using a `CentOS 5` but never got to it. In fact we are suffering pressure to upgrade it!

**Comment by karlmsmith** [comment]
I had given up on RHEL5 with this release of PyFerret, and v7.0 was going to be the last RHEL5 version for traditional Ferret.  So not worth the effort.  I mainly brought this up to see if ncurses was being linked in, but don't want to go down a long path of fixing for old OS's.

**Comment by ocefpaf** [comment]
@karlmsmith I am closing this since we cannot due `RHEL5` in `conda-forge`. Not that users that have that special need can re-build it using the recipe here if necessary.
