### ISSUE TITLE
Create the data package

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/pyferret-feedstock#17]
See https://github.com/conda-forge/pyferret-feedstock/issues/14#issuecomment-248125629

**Comment by karlmsmith** [comment]
I will create the NOAA-PMEL/FerrretDatasets github repo with these datasets.

**Comment by ocefpaf** [comment]
There is no need for that @karlmsmith unless it makes sense to your workflow. I can use the tarball released in https://github.com/NOAA-PMEL/PyFerret/releases/download/v7.0.0-final/FerretDatasets.tar.gz

**Comment by karlmsmith** [comment]
Since it is needed by both Ferret and PyFerret, and rarely changes, seems like a separate public repo makes sense.  If it someday it has an update, then that update could be detected for updating.  But for now just get that tarball.

**Comment by ocefpaf** [comment]
It is official. I am getting old! That was already done in https://github.com/conda-forge/ferret_datasets-feedstock

I can update it with your new repository once later BTW but this works for now.
