### ISSUE TITLE
Package clim data

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/pyferret-feedstock#2]
I did not check but I don't believe the data is shipped with the package. Maybe we need another package to install it separably. (Similar to what we did for `basemap`.)
- [X] add data
- [X] automatic env var setting for `conda-env`.

**Comment by ocefpaf** [comment]
Note to self: add `ferret_paths_template.sh` to the activate scripts so `ferret/pyferret` can be found when the env is activated.

**Comment by ocefpaf** [comment]
Note to self: add `ferret_paths_template.sh` to the activate scripts so `ferret/pyferret` can be found when the env is activated. The package is usable, but setting the manually editing and acting `ferret_paths_template.sh` and `pyferret_template` defeats the purpose of using conda.

![pyferret](https://cloud.githubusercontent.com/assets/950575/16699381/23a06160-452a-11e6-9930-056bb03d2c2b.png)

**Comment by karlmsmith** [comment]
Since conda installs pyferret in a well-known location(correct?), conda
versions of the pyferret and ferret_paths.{csh,sh} scripts could be created
and stored.
Many user also modify the pyferret script to source the ferert_paths
script, so that could be done as well for the conda-specific pyferret
script.
I also need to add the default datasets to that ferret/pyferret expects to
find to the GitHub repo to make this completely automated.

Karl

On Fri, Jul 8, 2016 at 12:38 PM, Filipe notifications@github.com wrote:

> Note to self: add ferret_paths_template.sh to the activate scripts so
> ferret/pyferret can be found when the env is activated. The package is
> usable, but setting the manually editing and acting
> ferret_paths_template.sh and pyferret_template defeats the purpose of
> using conda.
> 
> [image: pyferret]
> https://cloud.githubusercontent.com/assets/950575/16699381/23a06160-452a-11e6-9930-056bb03d2c2b.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/conda-forge/pyferret-feedstock/issues/2#issuecomment-231453253,
> or mute the thread
> https://github.com/notifications/unsubscribe/APpYx4y19xX_DIMMUPsDL2Tkwmnc7nHUks5qTqcggaJpZM4JITv6
> .

## 

Karl M. Smith, Ph.D.
JISAO Univ. Wash. and PMEL NOAA
"The contents of this message are mine personally and do
not necessarily reflect any position of the Government
or the National Oceanic and Atmospheric Administration."

**Comment by ocefpaf** [comment]
> Since conda installs pyferret in a well-known location(correct?), conda
> versions of the pyferret and ferret_paths.{csh,sh} scripts could be created
> and stored.

Yes. Something along the lines of https://github.com/conda-forge/pyferret-feedstock/pull/3

The activate/deactivate will create and remove the env vars as expected. Note that only works if the users is using conda environments! The user still needs to set them manually if using root env. (But the use of the root env is discouraged.)

> Many user also modify the pyferret script to source the ferert_paths
> script, so that could be done as well for the conda-specific pyferret
> script.

No need to do that for here b/c `conda-env` will take care of that for us. I also added the `pyferret` by default in the env `$PREFIX/bin`, so users can install `pyferret` and just call it no matter how they name the env. (Should we also add an alias named `ferret`?)

> I also need to add the default datasets to that ferret/pyferret expects to
> find to the GitHub repo to make this completely automated.

:+1:

**Comment by ocefpaf** [comment]
> I also need to add the default datasets to that ferret/pyferret expects to
> find to the GitHub repo to make this completely automated.

BTW, even if you add that to the repo, I think we should package it separately to avoid a big download when people want only `pyferret`.

PS0: I could not find a tarball for the data. Is that only somewhere?
PS1: The env activation scripts worked! If you do:

``` shell
conda create pyferret -n TEST_ENV -c conda-forge
source activate TEST_ENV
```

You can just call `pyferret` and everything should work without any extra user action.

**Comment by karlmsmith** [comment]
I have added FerretDatasets.tar.gz to the Downloads of the PyFerret v7.0.0-final release.

**Comment by ocefpaf** [comment]
> I have added FerretDatasets.tar.gz to the Downloads of the PyFerret v7.0.0-final release.

Awesome! Thanks @karlmsmith!! I will look into making a data package for `pyferret` soon.
