### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/pyferret-feedstock#44]
@karlmsmith I would like to try ti build `pyferret` on Windows but I'm not sure what is the best approach. Are you maintaining Windows builds somewhere? Do you use MSVC or may some sort of cygwin/msys2 gcc build toolchain?

**Comment by karlmsmith** [comment]
I make no attempt to support Windows.  Very old versions of traditional ferret were built for cygwin, but that was gone before PyFerret existed.

**Comment by ocefpaf** [comment]
Good to know. If there is no upstream binary I don't think we should try to do it here as well. (And there is always the Windows Linux Subsystem now ;-p)
