### ISSUE TITLE
conflict over libnetcdf with nco package

### ISSUE THREAD

**Issue by karlmsmith** [conda-forge/pyferret-feedstock#52]
PyFerret in the latest conda-forge pyferret package wants libnetcdf.so.15 (on a Linux system, under miniconda-python3) but the latest conda-forge nco package wants libnetcdf.so.13.  Installing both packages in the same environment ends up with libnetcdf.so.13 and so pyferret then fails with the message that it cannot find libnetcdf.so.15.  (My temporary hack solution was to create a symbolic link of libnetcdf.so.15 to libnetcdf.so.13 and everything appears to be working fine.)

I assume the quick and easy solution is to request an updated build of nco (and any other packages depending on libnetcdf) to use the latest libnetcdf library.

I didn't know if there is something missing in the pyferret configuration that we want to add, or if this is just "the way it is" - everything depending on an updated package needs updated builds.

Karl

**Comment by ocefpaf** [comment]
Something is bad in our pinning b/c installing them side-by-side should not happen.

The problem is that `pyferret` relies on `netcdf-fortran` and that is using latest `libnetcdf` while the whole conda-forge stack is not. Let me see if I can fix that. Hold on...

**Comment by ocefpaf** [comment]
@karlmsmith I removed the build number 4 and sent #53 to fix this for good in future releases.

**Comment by ocefpaf** [comment]
Done in #53.
