### ISSUE TITLE
New Development Build

### ISSUE THREAD

**Issue by seasage** [conda-forge/pyferret-feedstock#77]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
@ocefpaf, I'd like to build against the v7.6.4-beta tag in NOAA-PMEL/PyFerret, but the changes for the development version of the conda build seem not to belong to a specific fork. Should I make the changes for the build there anyway? If not, where?

Thanks!

**Comment by ocefpaf** [comment]
Did you push that tag to GH? I can only see https://github.com/NOAA-PMEL/Ferret/releases/tag/v7.6.0-beta

**Comment by seasage** [comment]
I pushed it here: https://github.com/NOAA-PMEL/PyFerret/releases/tag/v7.6.4-beta

**Comment by ngam** [comment]
Closing this.
