### ISSUE TITLE
New official release - 7.6.5

### ISSUE THREAD

**Issue by seasage** [conda-forge/pyferret-feedstock#85]
Hi @ocefpaf ,

I'd like to make an official release of 7.6.5. When you have a moment, could you take a look at the intel-mac.patch on the dev channel and see if you can figure out what's causing the build to fail? I wasn't able to reproduce the same error with a local build of PyFerret on my mac. Maybe there's something that's obvious to you that I've missed. 

It looks to me like the container on Azure is working with a different Fortran compiler version than what I've been testing on. Perhaps there's a way around that so we don't have to patch the conda build after the github release? I'd love to just keep everything current, but newer versions of gfortran really complain when they encounter some of the older PyFerret files.

As always, thank you for your help.

Best Regards,
Joshua

**Comment by ngam** [comment]
@josborne-noaa i have fixed the harffbuzz issue with a patch (and now we should proceed). I can try to help (I am significantly less experienced than ocefpaf tho).

Should I file (issue/pr) that little patch upstream as well?

**Comment by ngam** [comment]
@josborne-noaa can you also merge #86 when you get a chance pls? Then we can work our way up (probably place "bot-rerun" on the other two prs)

**Comment by seasage** [comment]
@ngam go ahead and file the patch upstream. I merged #86

**Comment by ngam** [comment]
Thanks! Do you want me to look inside dev branch and try to push forward? Which one are you interested in? v7.6.5-beta?

Also, is there an interest in expanding this to osx arm64 (m1 mac) and stuff like ppc64le?

**Comment by seasage** [comment]
Yes, please have a look. Let me know if there are any issues that appear to be coming from the PyFerret code, especially during compilation. You may see some warnings, but you can ignore those.

No need to expand it at the moment, but thanks for asking.

**Comment by ngam** [comment]
sounds good. I have fixed the dev branch last night. I will try to look a little more closely on the happenings upstream and see how I can help. Btw, I am associated with noaa as well and I paid attention to this feedstock because of some debate at our local lab about pyferret vs ferret and versioning, etc. 

For archs, etc.: There are automated ways to invoke arm and ppc rebuilds (I will experiment with them later, but I will want to check if there is anything fundamental in the way upstream --- it seems pyferret/ferret has never been deployed outside x86_64 and some 32-bit stuff? I will investigate, we can also push for newer builds from here and help upstream with support for more archs, etc. as time goes on)

**Comment by ngam** [comment]
xref: https://github.com/conda-forge/pyferret-feedstock/pull/83#issuecomment-990560614

**Comment by seasage** [comment]
Thank you! I really appreciate all this help.

That's true about the architectures it's been deployed on. Shoot me an email if you'd like anything cleared up in regards to Ferret/PyFerret. I'm happy to chat.

**Comment by ngam** [comment]
Wait... I see you merged the dev branch into main. I am super confused. This is not an official release, it says it's beta. 

There are two tracks in these feedstocks:
1. official release go to main and the bot actually handles the upgrades, etc.
2. beta / dev releases can have their own standalone branch and still get published.

What's your exact strategy? IMO, this feedstock should mirror exactly the upstream in terms of official/beta releasing. We should also have a `-beta` or `-dev` flag suffixed to those beta releases.  Copying @ocefpaf to clarify if I am wrong.

**Comment by seasage** [comment]
No, you're right.

**Comment by ngam** [comment]
> That's true about the architectures it's been deployed on. Shoot me an email if you'd like anything cleared up in regards to Ferret/PyFerret. I'm happy to chat.

Yes, I will get in touch privately at some point to explain internal noaa maters 😶‍🌫️ 

Let's close this issue for now. Continue at #88 to discuss add `-beta` or `-dev` suffixes, etc.
