### ISSUE TITLE
feedstock strategy

### ISSUE THREAD

**Issue by ngam** [conda-forge/pyferret-feedstock#88]
Sorry I have just joined and maybe I am not sure about our strategy in this feedstock. Copying this message from #85 (we should close those two outdated open issues now).

I see @josborne-noaa merged the dev branch into main. I am super confused. This is not an official release, it says it's beta.

There are two tracks in these feedstocks:

1. official release go to main and the bot actually handles the upgrades, etc.
2. beta / dev releases can have their own standalone branch and still get published.

What's our exact strategy? IMO, this feedstock should mirror exactly the upstream in terms of official/beta releasing. We should also have a `-beta` or `-dev` flag suffixed to those beta releases. 

Copying @ocefpaf to clarify if I am wrong.

--- 

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
I see we are reverting dev now #89. So, we are following the standard strategy of two branches, etc. --- we should design these merge requests so that they go from a personal fork to the appropriate branch. Let's also do some cleanup soon (adding suffixes) and improving the documentation in README (adding the dev urls, etc.)

**Comment by ngam** [comment]
@josborne-noaa please use a personal fork in the future: when the pr is a beta one it goes into the dev branch, otherwise into master :)

**Comment by ocefpaf** [comment]
@ngam you nailed it. Dev releases on a dev branch and with a dev label (all devs can go there, no need a branch for beta and other for alpha). The stable releases will go on master/main.
