### ISSUE TITLE
how to install pyferret sucessfully and use it in the jupyter notebook by Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by ruhuihuang** [conda-forge/pyferret-feedstock#96]
Hi there,
I just do as https://github.com/NOAA-PMEL/PyFerret/blob/master/README.md say, but I can not open it.
1.	pip install ferretmagic
2.	conda create -n FERRET -c conda-forge pyferret ferret_datasets --yes
3.	conda activate FERRET
4.     conda deactivate
5.	Then I Move into this PyFerret installation directory and run the bin/Finstall script to create the ferret_paths.sh。
6.     set the PyFerret environment variables. i.e. source ferret_paths.sh
 How ever when I "pyferret -nodiaplay" to open it ,it say:
          Traceback (most recent call last):
          File "<string>", line 1, in <module>
          ModuleNotFoundError:No module named 'pyferret'

7. if I try in the jupyter notebook, it also say ：
                                                                      ~/.local/lib/python3.9/site-packages/ferretmagic/__init__.py in <module>
                                                                      ----> 1 from .ferretmagic import *

                                                                        ~/.local/lib/python3.9/site-packages/ferretmagic/ferretmagic.py in <module>
                                                                          54 import tempfile
                                                                            55 import math
                                                                       ---> 56 import pyferret
                                                                            57 import base64
                                                                            58 from shutil import rmtree

                                                                       ModuleNotFoundError: No module named 'pyferret'

Any body can help me?

**Comment by ocefpaf** [comment]
Why did you deactivated the env in `4`? If you deactivate it you cannot use it.

You should:

1. `conda create -n FERRET -c conda-forge pyferret ferret_datasets jupyter pip --yes`
2. `conda activate FERRET`
3. `pip install ferretmagic`
4. either start `pyferret` or `jupyter notebook` and use the `ferretmagic`
