### ISSUE TITLE
how to install pyferret and use it in the jupyter notebook 

### ISSUE THREAD

**Issue by ruhuihuang** [conda-forge/pyferret-feedstock#97]
### Comment:

Hi there,
I just do as https://github.com/NOAA-PMEL/PyFerret/blob/master/README.md say, but I can not open it.
1.	pip install ferretmagic
2.	conda create -n FERRET -c conda-forge pyferret ferret_datasets --yes
3.	conda activate FERRET
4.     conda deactivate
5.	Then I Move into this PyFerret installation directory and run the bin/Finstall script to create the ferret_paths.sh。
6.     set the PyFerret environment variables. i.e. source ferret_paths.sh
 How ever when I "pyferret -nodiaplay" to open it ,it say:
          Traceback (most recent call last):
          File "<string>", line 1, in <module>
          ModuleNotFoundError:No module named 'pyferret'

7. if I try in the jupyter notebook, it also say ：
                                                                      ~/.local/lib/python3.9/site-packages/ferretmagic/__init__.py in <module>
                                                                      ----> 1 from .ferretmagic import *

                                                                        ~/.local/lib/python3.9/site-packages/ferretmagic/ferretmagic.py in <module>
                                                                          54 import tempfile
                                                                            55 import math
                                                                       ---> 56 import pyferret
                                                                            57 import base64
                                                                            58 from shutil import rmtree

                                                                       ModuleNotFoundError: No module named 'pyferret'

Any body can help me?
 
@jezdez @djsutherland @xhochy @msarahan @pkgw @karlmattsmith

**Comment by ocefpaf** [comment]
> @jezdez @djsutherland @xhochy @msarahan @pkgw @karlmattsmith

Please do not ping random folks from the conda-forge team. None of those can help you here BTW and the last one there is retired. Also, do not open multiple issues. I'm closing this one as duplicated of #96
